### ISSUE TITLE
stress does not work with DSE cluster

### ISSUE THREAD

**Issue by elijahsmith** [pcmanus/ccm#224] opened 2015-01-26 18:43 UTC
```
$> ccm create -v 4.5.2 -n 3 --dse --dse-username=*** --dse-password=*** dse
$> ccm start
$> ccm stress
Application does not allow arbitrary arguments: 127.0.0.1,127.0.0.3,127.0.0.2
```

This is on OSX and was reproduced. I *did* run the ifconfig statements needed on OSX.

**Comment by ptnapoleon** [comment] 2015-01-26 18:55
I assume the issue is that the stress command is using "4.5.2" as the cassandra version, rather than finding the version of the underlying Cassandra installation powering DSE, which would be "2.0.11". It should be a simple fix. I'll see if I can get it done today.

**Comment by ptnapoleon** [comment] 2015-01-26 19:52
@elijahsmith That was the exact issue. If you're willing to use the code in the `develop` branch, it is fixed now. Otherwise, a release should be out soon as a number of other problems have come up.

**Closed** 2015-01-28 15:51 UTC
Labels: Fixed in Develop
